# Generated by Django 4.2.5 on 2023-11-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentSoliq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='user2',
            field=models.CharField(max_length=300),
        ),
    ]
