# Generated by Django 4.2.5 on 2023-11-17 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserSoliq', '0002_alter_cashbacks_user'),
        ('PaymentSoliq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(default='8600', max_length=16, unique=True)),
                ('exp_date', models.DateTimeField()),
                ('card_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserSoliq.usermodel')),
            ],
        ),
    ]
