# Generated by Django 4.2.5 on 2023-11-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentSoliq', '0002_carduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='carduser',
            name='card_money',
            field=models.IntegerField(default=123456),
            preserve_default=False,
        ),
    ]
