# Generated by Django 4.2.5 on 2023-11-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surename', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=32)),
                ('PS_serial_num', models.IntegerField(unique=True)),
                ('PS_seria', models.CharField(max_length=2)),
                ('phone', models.IntegerField(unique=True)),
            ],
        ),
    ]
