# Generated by Django 4.2.5 on 2023-11-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserSoliq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbacks',
            name='user',
            field=models.CharField(max_length=300),
        ),
    ]
