# Generated by Django 4.2.5 on 2023-10-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserSoliq', '0002_alter_usermodel_ps_serial_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.IntegerField(unique=True),
        ),
    ]
