# Generated by Django 4.2.5 on 2023-11-01 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserSoliq', '0003_alter_usermodel_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where', models.CharField(max_length=255)),
                ('total', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('fiksal_id', models.CharField(choices=[('UZ', 'UZ'), ('LG', 'LG'), ('VG', 'VG'), ('NA', 'NA'), ('ZZ', 'ZZ'), ('EP', 'EP'), ('EZ', 'EZ')], max_length=2)),
                ('fiksal_belgi', models.IntegerField()),
                ('fiksal_seriya', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserSoliq.usermodel')),
            ],
        ),
    ]
