# Generated by Django 4.2.5 on 2023-11-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr', models.CharField(max_length=200)),
                ('where', models.CharField(max_length=255)),
                ('total', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('fiksal_id', models.CharField(choices=[('UZ', 'UZ'), ('LG', 'LG'), ('VG', 'VG'), ('NA', 'NA'), ('ZZ', 'ZZ'), ('EP', 'EP'), ('EZ', 'EZ')], max_length=2)),
                ('fiksal_belgi', models.IntegerField()),
                ('fiksal_seriya', models.IntegerField()),
                ('status_check', models.BooleanField(default=False)),
            ],
        ),
    ]
