# Generated by Django 4.2.5 on 2023-11-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckSoliq', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='user',
        ),
        migrations.AddField(
            model_name='check',
            name='usr',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
