# Generated by Django 4.2.5 on 2023-11-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckSoliq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='status_check',
            field=models.IntegerField(default=0),
        ),
    ]
